### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by kevin-jj** [ngmoco/ngcache#1]
Fetching git://github.com/ngmoco/ngcache.git
remote: Counting objects: 13, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 13 (delta 2), reused 13 (delta 2)
Receiving objects: 100% (13/13), 5.88 KiB, done.
Resolving deltas: 100% (2/2), done.
Fetching gem metadata from http://gems.github.com/.
Fetching full source index from http://gems.github.com/
Could not find gem 'ngcache (>= 0) ruby' in git://github.com/ngmoco/ngcache.git (at master).
Source does not contain any versions of 'ngcache (>= 0) ruby'

**Comment by ashleym1972** [comment]
Work on this was benched. We moved away from ActiveRecord and left the cache work to others.
